apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-04-24 - 14:17:20 +0000
  labels:
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/name: quarkus-camel
  name: quarkus-camel
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{required "A valid .Values.replicaCount entry is required!" .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0
      app.kubernetes.io/name: quarkus-camel
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2023-04-24 - 14:17:20 +0000
      labels:
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/name: quarkus-camel
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          #image: registry.hub.docker.com/niktz/quarkus-camel:1.0.0
          image: {{ required "A valid .Values.image.repository entry is required!" .Values.image.repository }}
          imagePullPolicy: {{ required "A valid .Values.image.pullPolicy entry is required!" .Values.image.pullPolicy }}
          name: quarkus-camel
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP      
          resources:
            limits:
              cpu: "0.1"
              memory: "128Mi"
            requests:
              cpu: "0.05"
              memory: "64Mi"    
      imagePullSecrets:
        {{ toYaml .Values.imagePullSecrets | indent 8 }}
