apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-04-24 - 14:17:20 +0000
  labels:
    app.kubernetes.io/name: quarkus-camel
    app.kubernetes.io/version: 1.0.0
  name: quarkus-camel
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: {{ required "A valid .Values.service.port entry is required!" .Values.service.port }}
      protocol: TCP
      targetPort: {{ required "A valid .Values.service.targetPort entry is required!" .Values.service.targetPort }}
  selector:
    app.kubernetes.io/name: quarkus-camel
    app.kubernetes.io/version: 1.0.0
  type: {{ required "A valid .Values.service.type entry is required!" .Values.service.type }}